# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrusel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(upload_to='carrusel')),
            ],
        ),
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('telefono_1', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=50, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('fondo', models.ImageField(blank=True, null=True, upload_to='fondo')),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(upload_to='galleria')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('Descripcion', models.TextField()),
                ('incluye', models.TextField()),
                ('precio', models.TextField()),
                ('imagen_1', models.ImageField(upload_to='servicios')),
                ('imagen_2', models.ImageField(upload_to='servicios')),
                ('imagen_3', models.ImageField(upload_to='servicios')),
            ],
        ),
    ]
