# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
