# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160330_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgenerales',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
