# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160331_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='slug',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='titulo',
            field=models.CharField(max_length=70),
        ),
    ]
