# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160330_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='slug',
        ),
    ]
