# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_servicios_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='servicios',
            name='imagen_1',
            field=models.ImageField(help_text='Esta imagen es la que se mostrará en la pagina de inicio', upload_to='servicios'),
        ),
    ]
