# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160330_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgenerales',
            name='preguntas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='privacidad',
            field=models.TextField(blank=True, null=True),
        ),
    ]
