# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160330_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='fondo',
            field=models.ImageField(blank=True, help_text='Esta imagen es la de fondo donde esta el menú', null=True, upload_to='fondo'),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='video',
            field=models.URLField(blank=True, help_text='El formato es el siguiente "https://www.youtube.com/embed/Cu4UsFqz6Q8"', null=True),
        ),
    ]
