# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160330_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrusel',
            options={'verbose_name': 'Imagenes Carrusel', 'verbose_name_plural': 'Imagenes Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='datosgenerales',
            options={'verbose_name': 'Datos Generales', 'verbose_name_plural': 'Datos Generales'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name': 'Imagenes Galeria', 'verbose_name_plural': 'Imagenes Galeria'},
        ),
        migrations.AlterModelOptions(
            name='mensajes',
            options={'verbose_name': 'Mensajes', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'Servicios y Precios', 'verbose_name_plural': 'Servicios y Precios'},
        ),
        migrations.RemoveField(
            model_name='datosgenerales',
            name='fondo',
        ),
    ]
