# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
