# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_promocion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='precio',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
