# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20160418_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='publicar',
            field=models.BooleanField(default=True),
        ),
    ]
