# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_promocion_publicar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajes',
            name='email',
        ),
        migrations.AlterField(
            model_name='promocion',
            name='precio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
