# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20160418_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosgenerales',
            name='video',
        ),
    ]
